from pathlib import Path

BIO_START_TOKEN = '[BIO_START]'
BIO_END_TOKEN = '[BIO_END]'
TRAINABLE_BIO_TOKEN = '[TRAINABLE_BIO]'
ANSWER_TOKEN = '[ANSWER]'
NUM_BIO_TOKENS = 2
BIO_TOKEN_LIST = [f"[BIO_{i+1}]" for i in range(NUM_BIO_TOKENS)]

SPECIAL_TOKENS = {
    'additional_special_tokens': [BIO_START_TOKEN, BIO_END_TOKEN, TRAINABLE_BIO_TOKEN, ANSWER_TOKEN] + BIO_TOKEN_LIST
}

CHECKPOINT_DIR = Path("checkpoints")
CHECKPOINT_DIR.mkdir(exist_ok=True)
